version: '2'

services:
  backend:
    build: .
    command: sh docker-entrypoint.sh
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONASYNCIODEBUG=1
    ports:
     - "6666:6666"
    volumes:
    - ./:/usr/src/app
  test:
    build: .
    command: sh docker-testentrypoint.sh

